# Generated by Django 4.0 on 2021-12-14 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary_one', models.CharField(max_length=250)),
                ('summary_two', models.CharField(max_length=250)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['published_date'],
            },
        ),
    ]
